workflows:
  android-workflow:
    name: Android Debug Build
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - name: Build Debug APK
        script: |
          chmod +x gradlew
          gradle assembleDebug
          #!/usr/bin/env bash
    artifacts:
      - app/build/outputs/**/*.apk
